import '../globals.css'
import { Inter } from 'next/font/google'
import { ThemesProvider } from '#/app/components/ThemeProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning lang="zh">
      <body>
        <ThemesProvider>{children}</ThemesProvider>
      </body>
    </html>
  )
}
